import { z } from 'zod/v4';
import type { VfxProjectRegister } from './vfx-project-tools.js';
const styles=['fire','water','water-petal','blood','cat','cosmic','cyber','cyber-grid','holy','ice','ink','light','lightning','poison','rock','void','wind'] as const;
export const SHIELD_VFX_TOOL_NAMES=['gripforge_shield_vfx','gripforge_shield_export'] as const;
export function registerShieldVfxTools(register:VfxProjectRegister,options:{apiUrl:string;getApiKey:()=>string|null|undefined},s:typeof z=z){
 const config=s.object({version:s.literal(1).optional(),style:s.enum(styles).optional(),radius:s.number().min(.15).max(5).optional(),stretch:s.tuple([s.number().min(.25).max(2),s.number().min(.25).max(2),s.number().min(.25).max(2)]).optional(),color:s.string().regex(/^#[a-f\d]{6}$/i).optional(),accent:s.string().regex(/^#[a-f\d]{6}$/i).optional(),intensity:s.number().min(.1).max(3).optional(),opacity:s.number().min(0).max(1).optional(),speed:s.number().min(.1).max(4).optional(),seed:s.number().int().min(0).max(65535).optional(),quality:s.enum(['low','high']).optional()}).strict();
 const common={workspace_id:s.string().max(100).optional(),config:config.optional()};
 const definitions=[{name:SHIELD_VFX_TOOL_NAMES[0],shape:{...common,save:s.boolean().optional(),idempotency_key:s.string().min(8).max(160).optional()},description:'ADMIN ONLY. Create an original editable 3D elemental shield using the shared shield-vfx module: 17 styles, radius/stretch, colours, intensity, quality and seed. Same shaders used in Studio and native exports. save=true by default queues persistent rendering/review/workspace save; poll generation_read for Studio URL. save=false returns an unsaved project. No commercial reference assets, collision or damage. Recipe compilation needs no AI; saving uses the normal VFX review pipeline. Work is not visually validated automatically.'},
 {name:SHIELD_VFX_TOOL_NAMES[1],shape:{...common,engine:s.enum(['threejs','godot','unity','unreal'])},description:'ADMIN ONLY. Compile a shield recipe into reusable native source files for Three.js, Godot 4, Unity or Unreal 5, using the same geometry and shader functions. Returns files keyed by relative path plus install instructions. Write ALL files into a dedicated directory; never overwrite an existing modified package without checking. Includes enable/hit/shatter runtime; no mannequin or preview environment. Native builds require target-engine verification; source export is not visual certification.'}];
 for(const d of definitions)register(d.name,{title:d.name,description:d.description,inputSchema:d.shape,annotations:{readOnlyHint:d.name.endsWith('export'),destructiveHint:false,idempotentHint:d.name.endsWith('export'),openWorldHint:false}},async(args,extra)=>{
  const key=options.getApiKey();if(!key)return{isError:true,content:[{type:'text',text:'GripForge API key required.'}]};
  const parsed=s.object(d.shape).strict().safeParse(args);if(!parsed.success)return{isError:true,content:[{type:'text',text:parsed.error.message}]};
  const {workspace_id,...body}=parsed.data as Record<string,unknown>;
  try{const r=await fetch(options.apiUrl.replace(/\/$/,'')+'/api/v1/vfx/shields',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,...(workspace_id?{'x-workspace-id':String(workspace_id)}:{})},body:JSON.stringify({...body,action:d.name.endsWith('export')?'export':body.save===false?'preview':'create'}),signal:AbortSignal.any([AbortSignal.timeout(90000),...(extra?.signal?[extra.signal]:[])])});const data=await r.json();if(data.studio_url?.startsWith('/'))data.studio_url=new URL(data.studio_url,options.apiUrl).href;return{...(!r.ok?{isError:true}:{}),structuredContent:data,content:[{type:'text',text:JSON.stringify(data)}]};}catch(e){return{isError:true,content:[{type:'text',text:(e as Error).message}]};}
 });
}
